### ISSUE TITLE
Plugin breaks with webpack serve watch mode + HardSourceWebpackPlugin

### ISSUE THREAD

**Issue by ganapativs** [stephencookdev/speed-measure-webpack-plugin#46] opened 2018-07-24 15:33 UTC
Plugin works nicely for initial build, but breaks when some file is changed and webpack/webpack-serve is watching for changes.

This happens only when `HardSourceWebpackPlugin` is included.

```
ℹ ｢hot｣: webpack: Compiling Done
ℹ ｢wdm｣:    1410 modules
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢hot｣: webpack: Bundle Invalidated
ℹ ｢wdm｣: Compiling...
[hard-source:core] HardSourceWebpackPlugin is using 177 MB of disk space.
✖ ｢wdm｣: TypeError: Cannot read property 'call' of undefined
    at Object.exports.call (/Users/guns/oooo/node_modules/hard-source-webpack-plugin/lib/util/plugin-compat.js:170:17)
    at Proxy.run (/Users/guns/oooo/node_modules/hard-source-webpack-plugin/lib/SystemArchetype.js:184:20)
    at args (/Users/guns/oooo/node_modules/speed-measure-webpack-plugin/WrappedPlugin/index.js:52:19)
    at _fn7.then._result7 (eval at create (/Users/guns/oooo/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:51:1)
```

Also if I remove `speed-measure-webpack-plugin`, everything works fine. let me know if you need more info.

**Comment by ganapativs** [comment] 2018-07-24 15:38
Just realised there is already a issue for this - https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/44

**Comment by stephencookdev** [comment] 2018-07-25 07:19
Okay cool, thanks for raising @ganapativs :) I'll close this as a duplicate of #44

and try my best to find some time to raise a code fix for this!

**Closed by stephencookdev** 2018-07-25 07:19 UTC
